theme: jekyll-theme-minimal
title: Python For Historians
description: Created for the German Historical Institute (London) by Kaspar Beelen and Luke Blaxill
image: imgs/institute_icon_small.png
logo: imgs/institute_icon_small.png
